### ISSUE TITLE
Can't test

### ISSUE THREAD

**Issue by Kal-Aster** [debascoguy/SearchEngine#1]
First: great work!
This package is huge... Actually beacuse of this it I can really feel the lack of a documentation...
It would be great to have this package installable via composer, but maybe I'll open another issue for this (I could even help for this!).

Meanwhile I was curious to test this but I really don't know where to start and I tried to open the example.php file, but of course I don't have the "test_database" in my mysql db.

So, would it be possible to add a sql file with the exported "text_database" example db for testing the library and trying to understand how it works?

**Comment by debascoguy** [comment]
Hi Giuliano,

I will update the package with a more detailed example and a sample
"text_database" sql file as recommended.

And Yes, you can help with the composer aspect of things.

Thanks,
Ademola Aina.

**Comment by debascoguy** [comment]
Issue is Resolved and Search Engine have been updated to PSR-4 and Supports newer version of MySQL. And the Sample DB have been addded to allow for easy testing.
